apiVersion: 1

datasources:
  # --- PROMETHEUS (MIMIR) ---
  - name: Mimir
    type: prometheus
    uid: mimir
    url: http://mimir:9009/prometheus
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Mimir
      manageAlerts: true

  # --- LOKI ---
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      # Link direto Log -> Trace
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # --- TEMPO ---
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    jsonData:
      httpMethod: GET
      # Link reverso Trace -> Logs
      lokiSearch:
        datasourceUid: loki
      # Link Trace -> Métricas (Service Graph)
      serviceMap:
        datasourceUid: mimir
      nodeGraph:
        enabled: true