{
 "title": "PHP-FPM",
 "description": "PHP-FPM",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(phpfpm_up,job)" } },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(phpfpm_up{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Since",
   "type": "stat",
   "description": "The number of seconds since FPM has started.",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_start_since{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Start Since"
    }
   ]
  },
  {
   "title": "Total Process Utilisation",
   "type": "gauge",
   "description": "Utilisation of processes based on active/inactive processes",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(phpfpm_active_processes{instance=\"$node\", job=\"$job\"}*100)/sum(phpfpm_total_processes{instance=\"$node\", job=\"$job\"}))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Accepted connections (rpm)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(phpfpm_accepted_connections{job=\"$job\",instance=\"$node\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Children reached",
   "type": "stat",
   "description": "How many times was the maximum amount of children reached?",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "stat",
   "description": "The number of idle + active processes.",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "phpfpm_total_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Start Since"
    }
   ]
  },
  {
   "title": "Process Request Duration",
   "type": "timeseries",
   "description": "The duration in microseconds of the requests.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "phpfpm_process_request_duration{instance=\"$node\",job=\"$job\"} ",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Process Last Request CPU ",
   "type": "timeseries",
   "description": "The %cpu the last request consumed.",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "phpfpm_process_last_request_cpu{instance=\"$node\",job=\"$job\"} ",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Proess Last Request Memory ",
   "type": "timeseries",
   "description": "The max amount of memory the last request consumed.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "phpfpm_process_last_request_memory{instance=\"$node\",job=\"$job\"} ",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "# of processes by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_state{instance=\"$node\",job=\"$job\"}) by (state)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_process_state{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration by process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_request_duration{job=\"$job\",instance=\"$node\"})",
     "legendFormat": "{{pid_hash}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Queued requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{instance=\"$node\",job=\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "timeseries",
   "description": "The number of requests that exceeded your 'request_slowlog_timeout' value.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "phpfpm_slow_requests{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Listen Queue Length"
    }
   ]
  },
  {
   "title": "Requests per process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(phpfpm_process_requests{instance=\"$node\",job=\"$job\"}) by (pid_hash)",
     "legendFormat": "{{pid_hash}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "# of Active & Idle processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{instance=\"$node\", job=\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of active processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_idle_processes{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "# of idle processes"
    },
    {
     "expr": "sum(phpfpm_total_processes{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "# of total processes"
    }
   ]
  },
  {
   "title": "Total process utilisation & container termination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{instance=\"$node\",job=\"$job\"}) *100) / sum(phpfpm_total_processes{instance=\"$node\",job=\"$job\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Process utilisation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "All stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "description": "The number of requests accepted by the pool",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "phpfpm_accepted_connections{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Accepted Connections"
    }
   ]
  },
  {
   "title": "Active Processes",
   "type": "timeseries",
   "description": "The number of active processes.",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 37 },
   "targets": [
    {
     "expr": "phpfpm_active_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Active Processes"
    }
   ]
  },
  {
   "title": "IDLE  Processes",
   "type": "timeseries",
   "description": "The number of idle processes",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 37 },
   "targets": [
    {
     "expr": "phpfpm_idle_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "IDLE Processes"
    }
   ]
  },
  {
   "title": "Listen Queue",
   "type": "timeseries",
   "description": "The number of requests in the queue of pending connections",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "phpfpm_listen_queue{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Listen Queue"
    }
   ]
  },
  {
   "title": "Listen Queue Lenght",
   "type": "timeseries",
   "description": "The size of the socket queue of pending connections",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 45 },
   "targets": [
    {
     "expr": "phpfpm_listen_queue_length{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Listen Queue Length"
    }
   ]
  },
  {
   "title": "Max Active Processes",
   "type": "timeseries",
   "description": "The maximum number of active processes since FPM has started",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 45 },
   "targets": [
    {
     "expr": "phpfpm_max_active_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max Active Processes"
    }
   ]
  },
  {
   "title": "Max Listen Queue",
   "type": "timeseries",
   "description": "The maximum number of requests in the queue of pending connections since FPM has started.",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 52 },
   "targets": [
    {
     "expr": "phpfpm_max_listen_queue{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max Listen Queue"
    }
   ]
  },
  {
   "title": "Process Last Request CPU ",
   "type": "timeseries",
   "description": "The %cpu the last request consumed.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 52 },
   "targets": [
    {
     "expr": "phpfpm_process_last_request_cpu{instance=\"$node\",job=\"$job\"} ",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Max Children Reached",
   "type": "timeseries",
   "description": "The number of times, the process limit has been reached, when pm tries to start more children (works only for pm 'dynamic' and 'ondemand').",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "phpfpm_max_children_reached{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max Children Reached"
    }
   ]
  },
  {
   "title": "Process Request Duration",
   "type": "timeseries",
   "description": "The duration in microseconds of the requests.",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "phpfpm_process_request_duration{instance=\"$node\",job=\"$job\"} ",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Process Reuests",
   "type": "timeseries",
   "description": "The number of requests the process has served.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 59 },
   "targets": [
    {
     "expr": "phpfpm_process_requests{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Proess Last Request Memory ",
   "type": "timeseries",
   "description": "The max amount of memory the last request consumed.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "phpfpm_process_last_request_memory{instance=\"$node\",job=\"$job\"} ",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Start Since",
   "type": "stat",
   "description": "The number of seconds since FPM has started.",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "phpfpm_start_since{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Start Since"
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "timeseries",
   "description": "The number of idle + active processes.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 66 },
   "targets": [
    {
     "expr": "phpfpm_total_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "timeseries",
   "description": "The number of requests that exceeded your 'request_slowlog_timeout' value.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "phpfpm_slow_requests{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Listen Queue Length"
    }
   ]
  }
 ]
}